webapp/user/models.py
from flask_login import UserMixin  # содержит в себе методы is_authenticated,
# is_anonymous, is_anonymous
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.model import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, nullable=False, index=True)
    password = db.Column(db.String(32), nullable=False)
    nick = db.Column(db.String(64))
    first_name = db.Column(db.String(64))
    last_name = db.Column(db.String(64))
    middle_name = db.Column(db.String(64))
    role = db.Column(db.String(64), nullable=False, index=True)
    superuser = db.Column(db.String(64))

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'

    def __repr__(self):
        return "<Пользователь: {}, ID: {}>".format(self.username, self.id)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember_me = BooleanField('Запомнить меня', default=True)
    submit = SubmitField('Отправить')

webapp/__init__.py
from flask import Flask, render_template, request
from flask_login import LoginManager

from webapp.model import db, Case
from webapp.user.models import User
from webapp.admin.views import blueprint as admin_blueprint
from webapp.user.views import blueprint as user_blueprint


def create_app():  # "фабрика" - функция которая создает Flask app, инициализирует его и возвращает app
    app = Flask(__name__)
    app.config.from_pyfile('config.py')  # считывает конфигурацию с файла config.py
    db.init_app(app)  # инициализация б/д

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'  # функция login будет заниматся логином пользователя
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(user_blueprint)

    # проверяем пользователя
    @login_manager.user_loader  # login_manager вытаскивает из сессионой cookie user_id
    def load_user(user_id):  # пeредает user_id и load_user
        return User.query.get(user_id)  # запрашиваем из б/д

    @app.route('/')
    def index():  # -> html
        return render_template('entry.html')

    @app.route('/write_db/', methods=['POST'])
    def write_case_db():  # -> html
        number_case = request.form['number_case']
        applicant = request.form['applicant']
        type_applicant = request.form['type_applicant']
        appraiser = request.form['appraiser']
        judge = request.form['judge']
        status_case = request.form['status_case']
        case_exist = Case.query.filter(Case.number_case == number_case).count()
        print(case_exist)
        if not case_exist:
            new_case = Case(number_case=number_case, applicant=applicant,
                            type_applicant=type_applicant, appraiser=appraiser,
                            judge=judge, status_case=status_case)
            db.session.add(new_case)
            db.session.commit()
            field_titles = ('ID', 'Номер дела', 'Заявитель', 'Тип заявителя',
                            'Оценщик', 'Судья', 'Статус дела')
            case_list = Case.query.all()
            print(case_list)
            return render_template('results.html', field_titles=field_titles,
                                   case_list=case_list)
        return render_template('results_error.html', the_number=number_case)

    return app

webapp/admin/views.py
from flask import Blueprint
from flask_login import current_user, login_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@login_required  # декоратор, если не аутентифицирован то перебрасывает на login_manager.login_view = 'login'
def admin_index():
    if current_user.is_admin:
        return 'Привет админ'
    else:
        return 'Ты не админ'

webapp/user/views.py
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user
from webapp.user.forms import LoginForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login/')
def login():
    if current_user.is_authenticated:  # если авторизован то перенапрваляет на страницу с index()
        #  is_authenticated - метод, но выглядит как атрибут, без ()
        return redirect(url_for('index'))
    title = 'Авторизация'
    login_form = LoginForm()
    return render_template('login.html', page_title=title, the_form=login_form)


@blueprint.route('/process-login/', methods=['POST'])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():  # проверка на ошибки, могут возникнуть при вводе данных пользователем в форму
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт")
            return redirect(url_for('index'))  # перенаправляет на страницу по названию ф-ции
    flash("Неправильное имя или пароль")
    return redirect(url_for('user.login'))


@blueprint.route('/logout/')
def logout():
    logout_user()
    flash("Вы успешно разлогинились")
    return redirect(url_for('index'))

webapp/templates/base.html
<!doctype html>
<html>
    <head>
        <title>{{ the_title }}</title>
        <link rel="stylesheet" href="/static/hf.css" />
    </head>
    <body>
        {% block body %}

        {% endblock %}
    </body>
</html>

webapp/templates/entry.html
{% extends 'base.html' %}

{% block body %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
    
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    
    {% endif %}
{% endwith %}

<h2>{{ the_title }}</h2>

<form method='POST' action='/write_db/'>
<table>
<p>ИС судебных дел</p>
<tr><td>Номер дела</td><td><input name='number_case' type='TEXT' width='60'></td></tr>
<tr><td>Заявитель</td><td><input name='applicant' type='TEXT' width='60'></td></tr>
<tr><td>Тип заявителя (введите число от 1 до 5)</td><td><input name='type_applicant' type="range" min="1" max="5" width='60'></td></tr>
<tr><td>Оценщик</td><td><input name='appraiser' type='TEXT' width='60'></td></tr>
<tr><td>Судья</td><td><input name='judge' type='TEXT' width='60'></td></tr>
<tr><td>Статус дела (Введите число от 1 до 5)</td><td><input name='status_case' type="range" min="1" max="5" width='60'></td></tr>
</table>
<p><input value='Отправить' type='SUBMIT'></p>
</form>
{% endblock %}

webapp/templates/login.html
{% extends 'base.html' %}

{% block body %}

{% with messages = get_flashed_messages() %}
    {% if messages %} 
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}   
    {% endif %}
{% endwith %}

<h2>{{ page_title }}</h2>
<form action='{{ url_for('user.process_login') }}' method="POST">
    {{ the_form.hidden_tag() }}
    <p>
        {{ the_form.username.label }}<br>
        {{ the_form.username() }}
    </p>
    <p>
        {{ the_form.password.label }}<br>
        {{ the_form.password() }}
    </p>
    <p>
        {{ the_form.submit() }}
    </p>
    <p>
        {{ the_form.remember_me.label }}
        {{ the_form.remember_me() }}
    </p>
</form>

{% endblock %}

webapp/templates/results.html
{% extends 'base.html' %}

{% block body %}

<h2>ИС судебных дел</h2>
<form method='GET' action='/'>
<table>
    <tr>
        {% for field_title in field_titles %}
            <th>{{field_title}}</th>
        {% endfor %}
    </tr>
    {% for case in case_list %}
        <tr>
        <td>{{case.id}}</td><td>{{case.number_case}}</td><td>{{case.applicant}}</td><td>{{case.type_applicant}}</td><td>{{case.appraiser}}</td><td>{{case.judge}}</td><td>{{case.status_case}}</td>
        </tr>
    {% endfor %}
</table>
<p><input value='Назад' type='SUBMIT'></p>
</form>

{% endblock %}

webapp/templates/results_error.html
{% extends 'base.html' %}

{% block body %}

<h2>{{ the_title }}</h2>

<p>Судебное дело</p>
<form method='GET' action='/'>
<table>
<tr><td>Дело с номер {{ the_number }} существует, поробуйте снова.</td></tr>
</table>
<p><input value='Назад' type='SUBMIT'></p>
</form>

{% endblock %}